name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: submodule update
        run: |
          git submodule update --init
          git submodule update
      - name: auto reconfigure
        run: autoreconf -fi
      - name: configure
        run: ./configure --with-oniguruma=builtin
      - name: make
        run: make -j8
      - name: make check
        run: make check
